### ISSUE TITLE
s04e07 修辞意识

### ISSUE THREAD

**Issue by liaodapo** [GC4WP/GC4grace42#11]
# 作业

学会使用隐喻，可以谈谈对于隐喻的理解，也可以写一个隐喻，**由小组的伙伴们互评**。

**Comment by liaodapo** [comment]
难以想象这是[大妈七分钟拉出来的屎稿](https://github.com/GC4WP/GC4grace42/commit/ca17ba249fb0f91bd4f80e0446b5f4fe43cbcaf8#diff-b0f7d2f0e771d334655480fcaad1c3e1)

**Comment by liaodapo** [comment]
同学们，这次的作业没有字数限制，可以只写一句，但要求小组互评。请大家摈弃往期样貌，尝试说出偏见，
展露愚见，
坦论成见，
说明识见，
抛出私见，
发散主见，
拔出利剑，
不要自闭。
要先怼后怂，
要先兵后礼，
要勇于风趣，不甚礼貌。
等见人再顺从，作网上蠕虫。
在心里拼命拱，对外面大力夯。

因为自闭的青蛙如果一直不跳出井口、去吃天鹅肉，它都不知道自己是癞蛤蟆。
因为地窖中的美酒如果一直不拆开饮用，会浪费。
因为封装好的牛奶如果一直不拆开饮用，会爆炸。

请大家勇于参与，对了，我这个里面有哪些是明喻、哪些是转喻、哪些的隐喻，我基础很差，谁能告诉我一下啊？

##
💥

**Comment by guoguodehezi** [comment]
### 比喻的整体性
——一个中学语文老师讲比喻

特别说明：以下观点来源于我自己的阅读体验，没有经过严格考据。

虽然王老师讲课用的是西方修辞学的系统，不过我还是比较习惯中国对于比喻的分类来理解比喻，因为比喻这个手法，可纯粹是土生土长的。追根溯源，脉络清晰。

汉乐府及其之前的诗歌，有一种手法叫做“比兴”，之后鉴赏很少提及。这就是比喻的源头。

详细说来，“比”和“兴”也是可以分开的。“兴”是起兴，也即在一篇或者一章开头部分，先言他物以引起所咏之词。比如“泛彼柏舟，亦泛其流。耿耿不寐，如有隐忧。”其实全诗是要写“隐忧”，却从“泛舟”写起。泛舟与隐忧有啥关系呢？能押韵大概也算是一种关系吧。诗歌的源头，就用这样的例子给我们示范了，语意在语音的河流上自在漂流的样子。

纯粹的起兴不好找，因为两件事完全无关，在宇宙中也是小概率事件。大多的“兴”都可以归类到“比兴”里。比如“桃之夭夭，灼灼其华。之子于归，宜其室家。”以桃花的烂漫比新嫁娘的妩媚。这里的“比”就是把两个不同事物放在一起，凸显了其中相同的特点。比的使用，看似引入了无关意象，使思维发散了，其实却有着聚焦作用。用得好，那就是“遗貌取神”：忽略掉无关的表面特征，而聚焦直击作者灵魂的核心特征，以期将同样的感动传递给读者。这大概也算得上“第一个把女人比作花”的天才吧。

比喻，作为一种修辞手法，它的哲学含义却是揭示了一个秘密：万事万物，总会在某一个维度上相通。而看似千差万别风马牛不相及的事物之间，也许还存在着更加本质的联系。它在等待着作者如同牛顿发现万有引力一样，通过一只名叫比喻的苹果，发现它。
这就是我所说的“比喻的整体性”的基础。没有任何一个比喻是孤零零存在的，或者说是以一个比喻句孤零零的就可以成立，它一定有它的整体背景。

比如《离骚》，直接让你背它，你肯定痛苦死了，但是只要告诉你整个离骚有个比喻系统，那就是“香草美人以比君子”，你一定会发现它写了一百种香草幽兰，也不过在说一句话，作者对美德（审美层面的）追求的执着。这是作者以内心的规则设定比喻系统规则，向外摘取外物的结果。有点像徒手打造一个世界的《冰与火之歌》——当然这个题目也是隐喻。

还有一种比喻，更接近“兴”的源头，那就是触景生情，即事设喻。作者并没有提前预设的比喻系统，就是看到什么，遇到什么就写什么，但是写下来，一样贴切生动，宛如天造地设。比如“月如钩，寂寞梧桐深院锁清秋”，一弯钩月，拢住帘幕，如同一个取景框。镜头一一拍过去，入镜的景竟然恰好就是心境的隐喻。不是诗人打造了天地，倒像是这方天地专为诗人打造的。

要说隐喻的整体性，无过于《红楼梦》，但我写不完，写完就是一本书，还是一本不用考证就可以知道，内容被前人重复过无数次的书。

所以在文章最后，我想用老师也用过的那篇《荷塘月色》来解释一下比喻的整体性。
所有批评《荷塘月色》比喻用的浅薄、莫名其妙的人，都是在割裂地看待其中的比喻。《荷塘月色》整体来看在说啥？就是作者心境的起伏。“不宁静”-出门求自由-受用荷塘月色-打破宁静-思江南-回到妻儿睡熟的家。这里他的心境构成了一个闭环，“出门”“进门”两个动作也有非常明显的隐喻。他在荷塘月色里享受的是不受世俗道德规范约束的，独处的自由。所以他不是一个画家，必须要画出一幅符合中国文人审美的美景；他只是一个卸下一切捆绑，逐渐袒露自己潜意识的普通人，只不过这个人手里有比喻这个工具罢了。如果他是一个音乐家，那就有可能是“二十四桥明月夜，玉人何处教吹箫。”

拿受诟病最多的这一组博喻来看，“正如一粒粒的明珠，又如碧天里的星星，又如刚出浴的美人。”很明显展示了他放飞自我的过程，“明珠”凸显圆润光泽，“星星”凸显神秘闪烁，两者结合起来不就是“皓齿明眸”的隐喻吗？第三个“刚出浴的美人”多么顺理成章。这里应该说说我对博喻的理解，博喻绝对不是并列地放上三个比喻就行了，博喻也有它的整体性，三者之间也应该是有联系的才对。由表及里，由浅入深地揭示事物不同层面的特征，所以博喻的最后一个，应该是最重要最石破天惊的比喻，甚至于前面都可以是铺垫，最后一个要抖包袱了。回到这一组博喻上来，他把什么放在了抖包袱的位置上呢？这还不明显吗？
至于说到后文“如梵婀玲上奏着的名曲”，有人认为极具中国文化特征的画面上，怎么出现了这么不和谐的一个比喻。其实这句话的前提就错了，评论者所持的“中国式画面”，绝对不应该有“刚出浴的美人”（唐寅的画除外）这样的形象吧？“梵婀玲”隐喻着什么呢？其实秘密藏在“名曲”里。月色下的梵婀玲，奏着的是求爱的小夜曲。
再结合引文“妖童媛女，荡舟心许”“低头弄莲子，莲子清如水”，人家朱自清文章明明是前后统一，整体比喻非常和谐的。批评者是先入为主地划定了这篇文章“应该”有什么特色，看到不符合自己预设的，就跳脚了。

**Comment by Karina-Han** [comment]
平行世界

------地球村是全球化进程中的想象共同体，当它被冰冷的现实击碎时，就现了原形，仅仅是一个个小小的世界，彼此并不相通。

十天前，我从房东家里搬出来，到朋友家居住。原因是澳洲疫情爆发，房东坚持上班，粗略计算了下群体免疫政策下，同住的人无防护上班，且ICU被挤爆的死亡风险：0.6X0.8X0.1=0.048, 高达5%，不能接受。

房东无法理解我为什么如此害怕。当时澳洲大概500例新冠肺炎，她觉得病毒离自己很遥远，因为她带了口罩，就算和不带口罩的西人们挤公去交上班也不用害怕。但是我没办法停止被感染的想象，口罩的防护作用只有60%，所以大家一起带口罩才有作用。

那些媒体上放弃病重者的案例，死亡数据，在我这里是真实的危机，在房东那里只是耸人听闻的故事，于己无关，完全不值得为此放弃生计，而我也没有权利劝她改变，只好改变自己，主动搬家。幸好我的朋友与我三观一致，非常怕死，出门买东西口罩手套齐全，回家消毒液擦拭，衣服物品阳台静置4小时。

在国内疫情严重的时候，我的父母都不一定能做到我这样，那些防护知识听听就过，那些感染病重惊吓过就忘记，只能感谢祖国抗疫有力，把大部分感染者隔离开，保护了我的父母。

朋友家远离市中心，是澳洲人喜欢的乡下大house, 带一个小花园，经常有小动物光顾。稀薄的大气层给澳洲带来了高强度紫外线伤害，也带来了美丽的天空，人们每天都能活在风景画里，晚上星星很多，非常适合在公园悠闲的散步，或者跑步。

平日的澳洲是悠闲的，所以疫情来了也不能阻止人们跑步，在公园聚会。每次路过公园，都能看到两个白发西人老太太坐在椅子上聊天，身边不时跑过零星的跑者，也许这是生活中为数不多的坚持。

当真实地处在这样的环境中，就无法将这种日常视为一种罪恶，如同社交媒体上的旁观者一般，举起抗疫的正义大旗进行控诉。今天，澳洲的感染人数接近五千，禁止两人以上的聚会，关闭非必要营业场所，关闭海滩，仍然没有禁止人们出去跑步，也许跑步在澳洲已经成为了一种文化，一种必需品，尽管现在它很有风险。

澳洲世界和中国世界是不同的，跑步在澳洲作为政治正确可以被原谅，在国内却是高风险行为，遭到微博人民一致抵制。那位在国内坚持跑步的澳洲华人女性没有注意到，不同文化下的世界是不同的，进入另一个世界，要遵守规则，否则就会遭到驱逐。

**Comment by Karina-Han** [comment]
我的天，这开头写得太大了，想写欧盟，想象共同体来着。
这么一写几千字打不住，放弃了......

**Comment by liaodapo** [comment]
聊颇、果果、王老师评论，大妈旁听的[录像](https://pan.baidu.com/s/1PWVshit6kj6qc9Rjdb61MA)
 
*提取码: cce9
