### ISSUE TITLE
s04e09 文体原本

### ISSUE THREAD

**Issue by liaodapo** [GC4WP/GC4grace42#13]
## 作业
按照《风格的要素》的核心要求，以小组为单位，创作一段文字，做到：

删除不必要的词

有生命力的作品是简洁的。一个句子中不应有多余的词，一个段落中不应有多余的句子，就像一幅画中不应有多余的线条，一部机器中不应有多余的零件一样。这不是说，作者只能写短句子，或者要避开所有细节，仅仅把主题勾勒出大致轮廓，而是说，每个词都必须有信息量。

内容不限，500字以内。

**Comment by liaodapo** [comment]
大妈的[作业](https://github.com/GC4WP/GC4grace42/blob/master/s04e09_dama.md)

**Comment by Karina-Han** [comment]
长句与短句

接触英文写作以来，最让我觉得突破认知观念的事情是长句与短句, 原来中国人认知里的短句和外国人认知里的短句是不一样的。比如我觉得短句应该是：我喜欢猫，四个字，对应英文“I like cat”简单句，要是我在英语考试里写出这样的句子，会因为简洁而给我高分嘛？不会，反而会因为我词汇量匮乏扣分，并且还要列举出喜欢猫的原因，以及为什么讲这件事。

那么英语里的不算长的的句子是什么样子的？王老师推荐的英语写作必读书籍《风格的要素》里的句子都是简洁有力，毫无冗余，堪称典范，我们来看下里面的句子：

> This requires not that the writer makes all his sentences short, or that he avoid all detail and treat his subject only in outline, but that every word tell.

29个字，是一个复合句，带从句的复杂句，但它在英语世界里是一个简洁的句子，在学术文章里是一个短句。英语世界的长句长这个样子：

> The physicist rightly dreads precise argument, since an argument that is convincing only if it is precise loses all its force if the assumptions on which it is based are slightly changed, whereas an argument that is convincing though imprecise may well be stable under small perturbations of its underlying assumptions.

这个句子摘自GRE阅读考试，总共51个字，考美国的研究生博士生都要对付这些句子，它们拥有较多的后置结构，常常令人分不清这个结构是属于哪个部分的，而中文中并不经常使用带限定句子的长句，所以中国学生阅读英语论文时会觉得很不适应，反应不过来，为此要经行长时间的训练。

学术文章里的句子虽然长，但它们并没有冗余的词，每一个词都是为了限定说明范围，使表达更精确，减少歧义和逻辑错误。当说明事实时，要说明使用范围，对象，条件，等等，否则这篇文章就会出现谬误，学术价值荡然无存。

英语是一门追求精确的语言，因此它非常适合用作学术语言，去描述那些有诸多限定的事实，让理论，假想，事实等顺利的在学术圈里流动，减少内容传输中的“失真”，提高研究效率。掌握了长难句，才能读懂那一篇篇人类智慧与合作结成的论文，才能在此基础之上进行学术研究，才能配得上全额奖学金。


所以短句不等于简洁有力，反而会因为没有限定条件而模糊不清；长句不等于冗余累赘，正是加上了限定结构而增强了表达力。

高晓松说英语国家在造纸术，印刷术普及后，因为写书成本下降，所以句子能写多长就写多长，某种程度上是对的，人们普遍认为印刷术为文艺复兴创造了条件。

**Comment by leyafo** [comment]
## 谈谈 oxford 一词的翻译
这两天偶然间发现 oxford 一词原来是 Ox(牛）＋Ford(较浅的水滩）组合起来的，难怪这个单词长得这么奇怪。oxford 翻译成牛津是直译，拆开 ox 和 ford 再仔细一品“津”这个字，忍不住直拍大腿，这翻译真的妙啊，直通信达雅。
根据 wikipedia 记载 oxford 完整的英文是 Ford of the Oxen 表示浅滩上的一群牛。如果让一个没文化修辞的大老粗（比如我）翻译这个词，大约会翻译成如下几个样子：
```
牛滩   
牛潭  
牛湖  
牛塘  
牛河  
```
以上所有翻译让五头牛反胃到吃草不香，并表示严厉抗议并拒绝。想想几百年后你的后代拿着的词典封页印着以上五个词语之一，这事必须要有文化的人来做不可。这时让人一下子难以体会其中绝妙的“津”字就出来了。不明白什么意思还是老老实实去查字典吧。
```
津
jīn
【名】
(会意。金文字形,从舟,从淮。“淮”表示淮水。泛指一般的河流。船停泊在河旁,用来渡河。本义:渡口)
同本义〖ferry〗
津,水渡也。——《说文》
又东至于孟津。——《书·禹贡》
自黄河泛舟而渡者,皆为津也。——《水津注·河水》注
风烟望五津。——王勃《杜少府之任蜀州》
孔子过之,使子路问津焉。——《论语·微子》
```
这下你脑子里应该会浮现一群牛心满意足的在浅滩上津津有味吃草的情景。

**Comment by guoguodehezi** [comment]
这次作业全都是美文诶！好好欣赏了一会儿。
亚夫的作品，我还想补充一点。中文词汇的联想义使字虽简短，但含义深远。“津”字本身具有的“渡口”含义，让“牛津”这个词跟它所对应的“大学”本质属性更加接近了。

**Comment by guoguodehezi** [comment]
### 抄经的格式演化

决定加入王老师的三年抄经计划，主要是因为风雨飘摇的内心需要一个稳定的锚。
之前对圣经并不了解，甚至受爷爷这个坚定的唯物主义者影响，一度对宗教有偏见。圣经原文没有读过，只是从其他文章里接触过圣经小故事。

开始抄经，我想过用什么格式，首先就否定了原来抄电影台词时用过的形式：上面英文下面中文，每句间隔空一行以便补充注释。因为这样每句一断，可能会隔断文本连续含义。

所以第一阶段选择了正面抄英文，背面抄中文的方式，一行英文占两行横格，背面中文落在没有写英文的那一行。这样背面透过来的隐约笔迹也不会重叠。
抄过一个本子之后，发现存在一些问题。先抄英文，我英文不好，有时候连猜带蒙还是会理解错。而写完一面再抄中文的时候，有些句子又忘了。还有，英文抄的太疏散，背面中文的内容就不多，看上去一页就像没写完。改进。

第二阶段，左面抄中文，右面抄英文，中英对照很方便。英文一行只占一行横线，只是在节与节间隔处空一行，这样纸面留有呼吸的空间，不至于太过密集，同时也提高了一页的容量。
这样抄了很久，也被一些问题困扰了很久。中文还是只有半页多，而且如果先写中文，就要提前数右页英文能写几节；如果先写英文，写中文的时候手就会蹭到墨。
还是需要改进。最近这几天，我咬牙放弃了中英对照的便利，采用了第三种格式。

第三阶段，还是左面抄中文，右面抄英文，但中文不再等齐英文的内容，就一段接一段往下抄。抄完一章中文，左面也开始抄英文。
感觉节奏加快了，抄起来非常顺畅，基本不用理会文本之外的格式限制。而且中文比英文快，大意都了解的情况下再抄英文，理解起来偏差也不会太大。继续试验。

题外话：关于本子的选择。其实就是在B5的大本子、A5的小本子、200页以上的厚本子、80页以下的薄本子，这几个元素之间的排列组合。所有组合都试过以后，觉得还是A5薄本子好用。翻页无障碍，手腕不容易酸。但是中间有一段因为自己抄的快了很多，就去抄了20多章旧约里的创世记，感觉旧约用B5厚本子有种原始社会的艰苦感。

**Comment by liaodapo** [comment]
## 自闭怪思春
匀称的身条，淳朴的声线，个性憨直能接纳所有人。再看到那张爽朗的脸，所有人都假想互相为情敌了。好在你清高自明，不参与任何社交，从爱情争夺战一开始就弃权。
但偶然看见那人的个性签名：“待人友善是修养，独来独往是性格”。你的心，动荡了。

你开始在脑中演练，说话的样子、表情和方式。约会的地点，一定不会是俗套了。你告诉自己：你有这个资本。
因为你在约会中很谨慎，会留意对方爱吃的水果、询问喝热茶还是冰酒。因为这样，你才能提前买好相应味道的糖果、调整口腔的温度，给与致命冲击的第一吻。
到你们离别时会暧昧眷绵、摆尽丑态，为蹩脚的理由受困于房间，再相互承诺出界线……截至你抚摸到胸前的痣，你才关掉手机，停止幻想。因为康庄大道上是不容许儿女私情的，你永远这样告诫自己。

##
🔎

**Comment by xysjou** [comment]
**跑步总结**

经过一个多月的长跑恢复期，四月中旬，我开始加速训练。

起初，我以五公里为提升目标。等忙完一天的工作，夜深回家，换好运动装，出门跑步。

起步一公里是长长的下坡路，我放开步子猛冲，跑完用时 4 分 06 秒。

第二公里，有两段岔路，在穿过其中一段 T 字路口时，出现小意外，红灯亮，我无法穿过，只能先在大马路跑一小段路程，再找准机会，靠近江边步道。用时 4 分 18 秒。

第三公里，我的身体发热，身型不稳，速度明显下跌，用时 4 分 55 秒。 

最后两公里，我沿江边往回跑，嘴巴大口呼吸，身体发烫，勉强跑完，差点晕倒，全程结束，总计 24 分 20 秒。

我站在井字路口往回走，总结这段路所遇到的问题：

1、很明显的是，下坡路我起步太快，放开速度，忽略了接下来 4 公里要有体力支撑；

2、前期用力过猛，导致身型极不协调，没有力气支持接下来的路程，只能跌跌撞撞跑完全程；

3、最后是心态，长跑切忌急躁，一公里的快慢并不重要，更重要的是学会平均分配速度。短跑才拼爆发力，长跑取胜靠耐力。

没想到我跑步这么多年，现在还会犯如此低级的错误，实在是操之过急。
