### ISSUE TITLE
s04e10 风格的要素之旧约

### ISSUE THREAD

**Issue by liaodapo** [GC4WP/GC4grace42#14]
## 作业
对照《风格的要素》前两章的内容，分析一篇本小组的人写的文章，看看有哪些需要改进的地方，形成一篇文字诊断报告，500字以内。

例如：甲同学喜欢写被动句，乙同学喜欢一句一段，丙同学喜欢使用大量的「我认为，我强调，我指出」。

**Comment by liaodapo** [comment]
翻阅往期作业，发现本组有位同学，特别喜欢使用“我”这个字。使用的次数屡列前茅，从未落于第二。平常讨论的时候，使用人称代词的次数，也稳居榜首。

问题的源因，可能来自文化底蕴过于缺乏、自我意识过于强烈、写作态度过于松散、或者一并都有。从而造成文笔唠叨，章体冗余、口语化等的问题。

但问题出现的根本，还是由于对此得混沌：
不知道这样做会造成具体什么后果，
不知道具体什么时候可以这样做、什么时候不能这样做。

所以如果要整改，可以在往后的读写中，尝试从以上角度去观察、解析、理解这个问题，学会去运用它。不要再对此一知半解。不要因为自己第一首诗的标题是《我》，就在往后的写作中都放入“我”。

> 聊颇一小时42分钟便秘稿
##
🎠

**Comment by liaodapo** [comment]
大妈的[小情绪](https://github.com/GC4WP/GC4grace42/blob/master/s04e10_dama.md)

**Comment by liaodapo** [comment]
聊颇喷粪：大妈这次的作业提出了一个问题，却完全没有解答的意思，把问题甩出来就溜了。结尾处连续地疑问，更像是在设问，但却揪断了设问的答案，中年人谨慎地选择把未来留给可能。

聊颇溜了

**Comment by xysjou** [comment]
https://github.com/GC4WP/GC4grace42/issues/3#issuecomment-586354212

> 在知道 作家之耳 这个概念前,
> 俺已坚持阅读42年了,
> 早已形成相对稳定的阅读模式,

大妈的写作，行文风格就像是写代码，喜欢用“俺”之类的词，具有高度的辨识，但有个问题是，文章的段落，是写完一段再空行，大妈的文章，是写一句空一句，既不是诗歌的规律，也不是广告文案写作的方式。

> 简单的说, 俺的阅读内容分三类:
> 技术
> 收集
> 娱乐

逻辑性，分类写作是大妈写作的规律。这有点儿向在给文章放置抽屉，一格格的进行归纳，也如同网站链接里的“/”（正斜杠）必须一层层的将文章罗列，才能形成一篇文章。我记得村上春树谈写作，说自己坐在桌子前，是从抽屉里拿出素材，大妈写文章的方式和他相反。

在大妈的写作里，完全摒弃了用隐喻、比喻之类的句子。文章里面还会添加各种索引，从写作上来说，完全是一种很新颖的形式，但不利于人阅读，人喜欢一页页读书，而不是通过连接，不断打开索引，去获取更新的知识。
