### ISSUE TITLE
s04e11 马丁路德与《风格的要素》

### ISSUE THREAD

**Issue by liaodapo** [GC4WP/GC4grace42#15]
## 作业

以「最远最绕的路通常才是抵达目标的捷径」写一篇510字的文章（含标点），字数不多也不少，小组互评。

**Comment by xysjou** [comment]
**《学网站建设的捷径？》**

学习难免走捷径。和朋友聊天，谈及学网站建设。我告诉他，准备按照一个两年课程学。他叫我给他看看。我发过去，他看完，表示出异议。

我给他看的课程，涉及互联网理论知识，网络知识，编程语言等。这些知识过于庞杂，完全没必要弄如此复杂。

他举例说，这套知识如同居家隔离期间，闲着没事，忽然要学做菜。做菜的方法很多，有人会告诉你，做菜可是一门大学问，首先你得知道有哪些菜系，它们有啥特点，要会选锅、菜刀、调料等。了解完一切知识，再选食材，最后选择要做的菜。其实最想做的一道菜是：凉拌番茄。有必要这么复杂吗？下载一个京东到家，点番茄，再去楼下买白糖不就搞定？为什么还要去学番茄是怎么种的，用什么土壤才能种出好番茄？

学网站建设有这么复杂吗？完全没必要，要学什么语言，找个零基础的免费视频看看，动手操作就行。如果要学建网站，先学前端的三大块：html，css， js，搞定这一层再深入。先学会抛开服务器，在自己的电脑上做一个网站，自娱自乐，再学习怎么把网站放到互联网上面，实现众乐乐。

学习要有目标，有方法，有取舍，计算机知识几乎每天都在更新，新知识出来，旧的会淘汰。不是说旧的知识不能学，也不是说理论知识不重要，重要的是，自己要先明白学习的范围。

**Comment by liaodapo** [comment]
大妈的[作业](https://github.com/GC4WP/GC4grace42/blob/master/s04e11_dama.md)

**Comment by guoguodehezi** [comment]
### 最远的路，还没走到头
小时候我就患有心理疾病，种种原因，没有正规就医。30岁之后，我希望通过学习心理学，部分解决自己的问题，实现带病生存。
先考了二级心理咨询师，学习培训的过程中，接触到中国现有的心理咨询/治疗的各种流派。并且对其中有代表性的精神分析和认知行为疗法继续深入学习、实践。
因为不满于心理咨询界各种理论自说自话，互相矛盾的现状，我决定考心理学的研究生，见识见识真正的学院派是什么样子。
开学第一课老师说：“我知道大家很可能是看了《梦的解析》才来考心理学的，但佛洛依德早已过时了。”
心理学其实是理科，现在前沿的研究会用到基因分析和动态脑部核磁。就算只用最基本的概念，也会把抽象概念具体化，落实到判断、反应、选择、动作等可定量测量的项目上。心理学研究能力，最显性的就是能够巧妙设计实验，证实或者证伪各种理论假设。
事实上我更困惑了。因为受实验对象范围所限，心理学实验可重复性非常低。简单来说，在A身上成立的理论，在B身上就不一定成立。写论文的时候更清楚体会到，只要量表发的范围够广，题目够多，总能从数据中找出一些规律来。
我不知道这些对治好我的病有什么帮助。
最终还是要回归本心，所以决定加入三年抄经计划，这条路，也才刚刚开头。
