### ISSUE TITLE
s04e12 青春

### ISSUE THREAD

**Issue by liaodapo** [GC4WP/GC4grace42#16]
## 思考题

看《阳光灿烂的日子》写出一篇500字以内观后感，小组互评。

**Comment by liaodapo** [comment]
大妈的[青春](https://github.com/GC4WP/GC4E05gDAMA/commit/88b7d13b940d12e43ea0d9cf73ed0f42df94f23c#diff-207fe108720edcabe6d8297e200bcf0b)

**Comment by xysjou** [comment]
**小孩子的夏天和成人无关**

记忆里和夏天有关的事，从来和大人无关。这些事儿我出来工作才慢慢明白。

《阳光灿烂的日子》拍摄了一个特殊时期，一个特殊年代的故事，这个故事在大人们的治理下，好坏难辨，但在孩子们的生活中，很难看见时代留下的印记。

青春期的孩子，进入夏天，浑身充满着雄性荷尔蒙的气息，挡不住生物开始进化的历程。时代在前进，孩子们依旧过着自己的生活，打架斗殴、仗义执言、讨论女性……看着马小军，就使我想起自己小时候的青春。

我的青春里，有过下岗、98 洪水、非典、512 大地震……父母眼里，这些是与国家相关的大事。可他们不知道，我记忆里的大事，始终是放暑假去乡里捞鱼、照青蛙、玩水、吃雪糕……哪天回家，不遭受母亲的质问与拷打，就是快乐的一天。记录历史的大事，远不如在日光下流一身汗快乐。

只是这样的日子现在真的远去了，当我成为大人，才明白青春里与自己毫无关系的事，慢慢变成自己的生活。

体内的荷尔蒙始终会在爆发后趋于平稳，动物再凶猛，关进笼子也会逐渐收敛凶相。成年人的世界，除去工作，就是人为制造青春记忆，其实很多青春，是我们曾经可以随意浪费的时光。
