### ISSUE TITLE
s04e13 写作与复利

### ISSUE THREAD

**Issue by liaodapo** [GC4WP/GC4grace42#17]
## 作业

《我使用的一种思维方法》500字，小组合作。

**Comment by liaodapo** [comment]
大妈的[17分钟](https://github.com/GC4WP/GC4grace42/blob/master/s04e13_dama.md)

**Comment by liaodapo** [comment]
## 蠢材的福音

我有很长一段时间认为自己体内有两个人，一个天才，一个我。我负责掌控身体，而他，偶有危机才出来撑一下场面。当他不在的时候，我为了不把事情搞砸，一般都选择模仿他，或者用各种方法勾引他出来。

发呆，是最常使用的方法，也是第一个学会的方法。

大概在小学三年级的时候，从来不写作业的我，突然要独立完成一篇作文。端好凳子，摊平纸和笔，然后就呆在那里想呀想，想到动画片都播完两集了，愣是连标题都没想出来。等到他可能也着急了，我脑子里才忽然闪过一念。

后来这篇作文得到了老师的当众表扬，靠的就是他的标题。我虽然在学习上倒数第一，却也成为了面对全班朗读自己作文的首例。

但天才对我来说始终是模糊的。我为了理解他阅读的各种文章，为了追寻他探索的各类知识，为了调用他尝试的各个方法。如今都已遗忘了大半，一部分是因为舍弃了，一部分则滋养了不知道长在身上哪里的茧。而他和这些茧一样，都长在看不见的位置，又长期存在，导致我已经慢慢将他忽视……

但发呆依然是好用的。比如上次我找老板问加薪的事，老板说：“小杰呀，最近的情况你也知道。不是我不想帮你呀。”，我没回话，立马开始发呆。

老板看我一会，继续说：“是，你成绩确实好，成绩好就应该多鼓励，不可能说成绩好的人拿的还比别人低……”， 我继续发呆。

老板说：“公司也确实是比较紧张的……”，我发呆。

“那行吧，我先把你的要求提交一下。”

“谢谢老板！”

##
✔今年的感叹号额度用完了。

**Comment by ZoomQuiet** [comment]
@liaodapo 是也乎,(￣▽￣)

为什么不 push 到仓库中? 这样没办法点评哪...

发呆是行为吧, 不是方法.
