### ISSUE TITLE
s04e02  我是这样训练作家之耳的

### ISSUE THREAD

**Issue by ZoomQuiet** [GC4WP/GC4grace42#3]
## 要求

- 以小组为单位，讨论自己用来磨练作家之耳的作品。
    + 每组写至少500字。
- 两次作业提交日期都是：2020年2月21日
- 交作业方式：发送邮件到 coursework@bitcron.com
- 文章会自动发布在 haozhongwen.com

## 计划

- 200217 前, 各自回复 Issue 提交自己的 500 字
- 200218 晩, zoom 会议内部讨论明确小组内容主体
- 200221 前, 轮植主笔尝试多次和合
- 200221 2042 提交作业

## 追踪

- 200215 1942 快速答疑录音/像 链接:https://pan.baidu.com/s/1_IJ5O9xiUaAG1y4y3gGCow  密码:392j

## 终稿
- http://haozhongwen.com/post/gc4/2020-02/2020-02-21-18-41-31

**Comment by ZoomQuiet** [comment]
## 是也乎
> DAMA 的自我观察

在知道 `作家之耳` 这个概念前,
俺已坚持阅读42年了,
早已形成相对稳定的阅读模式,

所以, 只能根据这个新概念看哪些习惯吻合, 以便加强;
哪些不对, 从而纠正;

简单的说, 俺的阅读内容分三类:

- 技术
- 收集
- 娱乐

### 技术
> 所有为了解决已知任务而进行的阅读

- 无论开发/管理/演讲/求婚/...
- 各种场景中触发的任务
- 都习惯性采购主题图书:
    + 一般根据推荐或是以往积累的常识
    + 对领域主要权威作者/机构/组织/出版的图书
    + 一次性买多本回来
- 短期快速完成阅读, 高亮标记出当前任务相关部分
- 并立即实验,检验效果
- 这样能立即对陌生领域知识获得大致结构性了解
- 从而能发现/设定一个可行路线开展有计划的探索
- 这其中, 对文笔的积累,可能就是 `翻译乃大道` 那本书中详细讨论过的
    + 对翻译腔和精当的翻译
    + 有了足够语感
    + 能分得的出好歹
- 可惜, 多数技术图书都是由非专家快速用工具翻译过来的
    + 只能自己使劲脑补
    + 或是拿来原著对比理解

### 收集
> 所有为了解决还未到来的任务而进行的阅读

小时梦想就是成为 `凡尔纳` 小说中万能的博学家

所以, 在接触到互联网后, 就自觉的开始下意识的收集以及阅读;
这应该是中学写小说时, 不得不自制剪报来组织材料形成的习惯;

只是,现在俺能通过浏览器插件工具来辅助我完成:

- 无论在什么渠道遇到好文章/资料
- 及时回到桌面, 用浏览器访问
- 先批量将所有相关网页抓取到本地, 并用树状目录组织好
- 然后, 有空时, 和主题式图书阅读类似
- 也是按照一个主题快速广泛的将所有相关本地管理的页视都看一次
    + 过程中, 触发其它网站/文章/资料时
    + 使用相同流量一层层, 一级级
    + 逐一挖掘出来, 组织下来
- 只是, 不立即进行实验
    + 等到有机会, 有相关任务到来时
    + 就可以迅速进入有印象的对应目录
    + 根据以往速读的标记
    + 从最可能实现的线索进入, 快速建立检验
- 当然, 因为职业关系, 这种收集-快速浏览 基本都是技术相关
- 对文笔实在积累不大
    + 因为多数最关注的都是各种代码片段
    + 或是配置脚本...
- 不过, 这个经历现在好象积累为 Markdown 写作习惯了
    + 因为 md 的格式也是以缩进为主要结构表述
    + 和 Python 代码天然一致
    + 导致俺写文字,也越来越象代码的形式以及结构


### 娱乐
> 所有为了解决不可能到来的任务而进行的阅读

小时另一个梦想就是漫画家, 

    而漫画即万画
    万事万物皆可画

所以, 必须先成为博物学家;
好漫画当然要先有个好故事以及对应脚本;

好故事, 除了自己多经历万物外, 阅读当然也就是最高效的积累渠道了:

- 漫画本身就是最对口的阅历积累:
    + 从以往采购收集,到多次搬家只有最经典作品镇宅
    + 现在用是 Kindle 32g whitepaper 10代为主力
    + 通过付费服务导入漫画
    + 挤时间刷:
        * 经典完结漫画重刷, 回顾儿时记忆
        * 经典长筹漫画连载, 追了20年的漫画不得不继续追
        * 全新作者, 全新故事和画面, 对比各种漫改影视, 积累画面感
- 各种小说, 先是实体书阶段, 将各种知名作家全集都刷过后
    + 只留了 王朔/池莉 全集在家
    + 其余基本电子化
    + 开始研读 中国传统相声大全
    + 因为, 有关说话的艺术形式, 在中文世界, 最高成就就是传统相声了
- 从09年得知 DUKU(读库 ~ 一种 MOOK ~ 杂志式图书), 就开始收集/跟读:
    + 有全套 0600 开始所有 DUKU 正本(每年7本,至今98本全有)
    + 以此为线索触发接触到各种以往无法想象的体裁
    + 比如 "传家：中国人的生活智慧"
    + 又比如: [王南“建筑史诗”系列9册套装，一西一中介绍古今建筑_](http://www.duku.cn/product-2513.html)
    + ...
    + 从这一愉快的追读过程中, 接触到各种文笔和世界
    + 真正休会到私人文库的作用
- 另外, 日常通过 多看 电子阅读应用, 长年刷各种类型的网络小说
    + 在起点之前, 就发现可以下载到各种小说 .txt 格式, 
    + 上传到手机就能通过合适的阅读应用, 在各种碎片时间中, 保持不间断的完整的阅读体验
    + 而且字体/背景/间隔/翻页/...都可以配置时
    + 最终能形成最吻合自己习惯的高速阅读文字流...
    + 到现在已经是每周至少要达到 **200万字** 的阅读量(平均每周累计12小时左右)
    + 发觉越来越多历史/经济/地理/政治/生物/物理/文学/影视/...几乎所有行业常识
    + 都来自网络小说的阅读了...
    + 这可能是俺选择小说, 尽可能不看同类内容的原因
        * 同时, 也不看200万字以内的作品, 
    + 文笔上也发现, 有太多不知名作者竟然在长期持续写作中, 依然保持了不弱于专业作家的写作风格
- 甚至于很多生僻字,以及民俗, 也都是从网络类型小说中看到的...
- 这相比看纪录片还要快, 因为, 不占用专门时空和机器,
    + 随时在手机上就可以刷几页, 上千字...


以上, 这是俺现在的阅读类型和习惯以及工具;

但是, 其中有多少对作家的形成有帮助?

这可能是更加艰难的一个问题,因为必须有对应作品先产生, 才可能回溯出对应积累.

**Comment by guoguodehezi** [comment]
果果
耳边的朋友
“我是怎样磨炼作家之耳的？”抱歉这个问题我无法回答，因为我从来也没想过能够成为一个作家。
那么读书是为了什么？还是一个难题，难在说来话长。
一年级暑假，学校教学实验，让家长帮助拿下了常用三千字，从此打开阅读大门。到三年级基本上把爷爷书架上的书扫了一遍。说基本上，是有一套马克思恩格斯全集实在看不下去，没有读完。包括完全读不懂的《文心雕龙》，我把它当做了《九阴真经》、《葵花宝典》（毕竟都是四个字的）一类的书，都硬啃了下来——还是完全不懂。
你问一个小学生哪来的时间读这些？很简单，我没有朋友。也就是当年不太流行带孩子去诊断自闭症，我这个漏网之鱼才混在正常人里长大了。
说到这一波阅读里留下深刻印象的，有鲁迅的一套单行本，四大名著里的《西游记》《红楼梦》，版画插图的安徒生童话，《简爱》，绣像影印本《聊斋志异》。这就是我精神世界的底色。
以上虽然排名不分先后，但是在之后岁月里陪伴我时间最长的还是《红楼梦》。与其说它帮我磨炼作家之耳，不如说它是我漫长灰暗童年里耳边的朋友。
假期时间长，好嘞，来一遍；偶尔闲下来，不错，翻两页；生病在家呆着，林妹妹来陪陪我。有一次生病时挑了也很喜欢的《聊斋》，读了一个下午，只觉得天昏地暗，病更重了。还是《红楼梦》最适合耳鬓厮磨。
以后的阅读大概也就是这个模式，全凭运气的海量阅读，遇到好书也会时时回顾。值得一提的一次神奇经历，是关于《百年孤独》。
高中，某天下午放学，大家一起去一个同学家玩，打牌下棋各有所乐，不出意外还是把我一个给剩下了。我去她书架上随手抽出了这本书，就保持着那个站在书架前的姿势，赶命一般把这本书读完了。大概有一个多小时？对我来说真好像过了百年。那天回家脚底下都是飘的，眼前仿佛正吹着那场抹去一切的大风。从此以后再不敢碰这本书。
直到多年之后，据说是引进了版权，终于鼓起勇气买来了范晔的译本——这是我今生在买书上做出的最错误的决定——原来鲜活飞扬在眼前的段落，一字一句化为粉末。我只能说“这不对”，但原来是什么样，再也想不起来了。
如果说书是我的耳边之友，这一次，我想我亲手杀死了一个朋友。

**Comment by Karina-Han** [comment]
By Karina
磨练作家之耳的作品——《地球编年史》

在我的认知里，读书是一件好事，可是知道不等于做到。人生里大量阅读的时段在小学到初中，那个时候家里管的严，开学期间禁止看电视，用电脑，于是“看闲书”就成了为数不多的爱好，读过的严肃阅读书籍，多是在那个时期阅读的，还记得熬夜看鲁迅文集，不管自己看不看得懂，都让父亲从图书馆借回来。后来年纪渐长，操心的无聊事也多了起来，加上注意力在网络时代严重损耗，几乎只能读进去“爽文”，严肃阅读一年也读不了几本。幸好还有改变的愿望，于是想从一些类严肃阅读的书籍开始。

《地球编年史》系列一共有8本，7本研究成果，加一本名词解释。其内容争议非常大，因为作者的7本著作都论证了一个主题：人类起源于外星文明。作者撒迦利亚·西琴 攻读过考古学，历史学，语言学及神话学等，是世界上少数能破译苏美尔文字的学者，同时也精通希伯来文等欧洲语言，而他的论证材料也来自于考古发掘出的苏美尔等古文明文献，同时对照圣经等神话著作，以及一些古文明的遗迹。

有不少人将这系列丛书称为“科幻”，但其依据却来自于考古，文字学，《圣经学》的最新研究成果，作者将这些山一般的资料组织起来，去证明远古众神正是创造人类的“外星人”，而苏美尔神话，《圣经》，皆是人类对“众神”在地球上生活的记忆。历史上确实有很多巧合，成为作者“穿凿附会”的材料，比如人类的进化链：猿，人类的祖先出现于2500万年之前，大约1400万年前像类人猿转变，从那时起进化了1100万年类人猿才真正出现。3万年前的“尼安德特人”和类人猿的“南方高级古猿”非常相似，在以千万年为变化的进化链里非常正常，而智人是突然出现在3.5万年的，并且一出现就与现代人十分相似。书中这类巧合数不胜数，读起来和阴谋论一样，非常有意思。

但这本书的价值在于作者本人深厚的古文献知识，和考古学知识，这些材料单独阅读也许会比较枯燥，可是他们被作者用来讲“神是外星人”这样的故事后，就变得很有趣，于是读完未必会相信“人类是外星人创造的”，各种文明的神话故事会记住很多，也能进一步了解这些神话背后的民族，文化。

希望读完这7本书后，我的耐心渐长，能够啃下更硬的大部头。

**Comment by liaodapo** [comment]
《全合书》举世之作

今天我要谈论一部奇作，它的篇幅之大，大到我研读十余年却依旧不见深浅。它涵盖世界上的大部分知识，不光磨练技艺、增长见识，还能指引你完成世界上大部分事。许多阅书无数的牛人也常为其篇幅悲叹：真是太多了，怎么会这么多字。

读这本书需要强大的定力，因为其丰富的色彩会让你一不小心就偏离方向：我基本能在上面找到大部分我想要的，以及排山倒海式我不想要的。导致我常常应接不暇，本来还在看山清水秀，一会又开始玩起泥巴。最后泥巴玩得不出彩，山水看得不明白。

读这本书需要宽广的胸怀，因为它会同时赞美和贬低你的信仰：每当我试图攀登其中的山岳、探寻神秘的奥妙，我总能在出发之前，就饱瞰神被诟病。假如要在上面学折纸花，它会同时让你看到最美丽的作品，让你听到，这是朵没有香味的假花。然后再听到真花的娇柔，再听到假花的做作，没有一处安定，仿佛心悬在空壳。

如果没有定力和胸怀，读这本书时，你将陷入知识的漩涡。不光什么都没得到，日子也耽误了。

好在我已研读此书十余年，个中窘境渐云开雾展，能做到不再为海量的知识所惊怯。时而看山，时而塑泥，反而自在；
能做到欣赏假花，漫嗅真花，为不立场而苦恼；
能勉强做到主要抓住当下的，随时变动未来的；
能勉强做到学时究，爱玩玩；

能在文章的最后，轻易地告诉你：如果搜索此书，会发现怎么也不着线索。是因为它就是互联网本身。

**Comment by xysjou** [comment]
### **我是这样训练作家之耳的**

写作不是无根之水，必须要找到源泉，从中吸取营养，滋润自身。

我训练作家之耳的第一个方法是：阅读。

阅读是训练作家之耳的好办法，但人生有限，书的种类太过丰富，不得不选择性阅读。我的阅读并不丰富，从早年的《十万个为什么》《世界未解之谜》起步，到网络小说，武侠小说，慢慢开始向文学、历史等。

反观作家们的阅读历程，他们很早所接触的书籍，并不是像我这样。张爱玲一直在读《红楼梦》，艾米丽·迪金森以《圣经》为终生的写作范本，村上春树很喜欢《了不起的盖茨比》……所有的作家，在创作过程中，拥有训练作家之耳的书籍。它们会反复阅读，不断从书中汲取营养，从而不断滋养自身。作家一生会读很多书，但很多时候，会反复读一本书。哪怕这本书是一本字典。

成为作家，除了阅读，还有就是：写。

起初可以从模仿开始，比如找一本喜欢的杂志，开始模仿上面某个栏目去创作，写出刊登的标准。也可以模仿一些作家的文风，按照自己的笔调，去试着写。

写的过程，会有很多烦恼。我的方法是：散心。散心可以是随意走走，也可以去跑步。等做完这一切，再坐在桌子前，会有意想不到的灵感。

简单来说，我训练作家之耳的方式很简单：读和写。只有知道自己需要阅读什么书，才会明白自己要成为什么样的作家。再之后就是写，写不是一次就能成功，需要不断，反复的修改，这过程会有很长的时间。因为不是每个人都能像村上春树那样能坚持四千字，写到卡壳，自然需要做些额外的事。

至于有没有其他更快的写作方法，很遗憾，我到现在也没发现，希望有人能告诉我。
