### ISSUE TITLE
s04e03古典文体 修昔底德之今日武汉

### ISSUE THREAD

**Issue by guoguodehezi** [GC4WP/GC4grace42#7]
课后作业：s04e03

以小组为单位，用古典文体的标准分析《伯罗奔尼撒战争史：第七章瘟疫》。

假如修昔底德穿越到今日之武汉，他会怎么写？

请以修昔底德的笔法写出500字。

**Comment by Karina-Han** [comment]
by Karina

2019年12月，距离春节不到2个月，人们渐渐进入了年末的放松状态，制定了各种出行旅游计划，浑然不知一种病毒已经悄悄在武汉传播。最初发现这件事的，是湖北医疗前线的医生们，他们发现前来就诊的肺炎患者有着与SARS一样的症状，身经百战的一些医护立刻察觉到这应该是一种传染疾病，于是选择立刻上报，这些疾病的消息只在医疗系统内部流传。

在这一月内，不明原因肺炎越来越多，多数患者来自武汉华南海鲜市场，医生在他们的肺泡灌洗液中提取出了SARS冠状病毒。最开始感到不安的，还是医院工作的医生们，他们私下交流病情，已经感觉到不明肺炎是可以人传人的，有的医院为医生们准备了更高等级的防护设备，也开始隔离肺炎患者，12月30日，武汉卫健委下发相关通知，要求未经授权任何单位，个人不得擅自对外发部救治信息。有的医护人员没能遵守这个规定，向自己的亲朋好友发出警告，说有SARS传染病，公安系统将违反通知的8名医护人员定性为造谣，要求签署一份关于互联网不实言论的《训诫书》，这其中包括李文亮医生在内，他也准备接受医院的处分。同时，各大电视台通报，对8名传播造谣SARS的人进行了处罚。

辟谣的消息总是能让人安心，人们也愿意相信，经历过非典后，这个国家不会再一次让传染病肆虐。并且武汉有一个全国第一的P4级病毒研究所，微博大V江宁婆婆表示“如果武汉搞不定，没人搞不定”，这也给网友们带来了安慰，认为这只是小规模传染病，并痛斥造谣者心怀不轨。

1月3日前后，湖北专家与一线医生制定了不明肺炎的诊疗方案，为该传染病的确诊制定了一条非常严格的标准：与华南海鲜市场有接触史。当时已经存在很多病患并没有华南海鲜市场接触史，于是他们不被认为是传染病病例，未被隔离，有的患者退烧后就回家了，与他们密切接触的家人也没有接受检查。这个时候的医护人员并没有进行特殊防护，在接触病人的过程中，也感染了疾病。 根据武汉市卫健委的公告，此时不明原因肺炎诊断患者44例，重症11例。武汉市两会也在此时召开，期间没有新增病例。

起初，人们并没有意识到这是一场灾难，还在为即将到来的春节做着准备，许多在春运期间从武汉回到自己的家，或者是趁着长假进行家庭旅行，1月18日，武汉时江岸区百步亭花园社区还举行了万家宴，4万多个家庭一起共度农历小年。次日，新增病例17例，武汉市疾控中心主任表示，该疫情持续人传人的风险较低，疫情是可防可控的。到了20日，之前的不明肺炎，新型冠状病毒确诊病例突然达到了136例，武汉以外的多个省市，甚至国外也持续不断地出现了患者，人们发觉疫情比想象中严重，23日，武汉封城了。

封城的消息让毫无准备的人们措手不及，火车站排队的人们一脸茫然，大量疑似患病的武汉市民涌到了医院，在病患人挤人的情况下，发生了交叉感染，许多本没有患病的人被感染，湖北武汉决定建立”小汤山”模式临时医院，医疗物资也开始告急，许多医院向社会发出紧急求助物资支援。人们对于医院求助这样的信息很迷惑，这与湖北省长说的物资储备供应充足不符，并且没有预料到情况紧急到需要直接捐物的地步。

新型冠状病毒的症状非常奇怪，它似乎并不像非典SARS病毒那样，有着高致死率，有的人症状比较轻微，只是发热，有的人一点症状都没有，这也为确诊和控制传播带来了困难。在更严重的情况下，会导致严重的肺炎，患者需要呼吸机，甚至体外呼吸肺。这样的病症在医疗资源充足的情况下并不难治疗，在美国，澳大利亚等地区，目前为止并没有出现患者死亡的情况。但是在病源地武汉，该疾病传染的人数多，情况复杂，并且该地发生了医疗资源挤兑现象，导致新冠病毒致死率为其他地方的30倍，在这样的情况下发生了很多惨剧。

大量武汉病患无法就医，他们会在医院门前排几天的队，有的人在排队途中就去世了，还有人死在了医院的走廊里，他们只能上网求助，请求一个床位。有的病患在家中过世，家人不知道如何处理尸体，殡仪馆并不具备消毒设备，社区里无人可做这样的工作，同样也是通过网络球员。还有的病患因为害怕感染家人无法回家，又没办法住院，只能在街上流浪，甚至选择轻生。有位导演，父母先被感染去世，最后自己和妻子相继感染趋势，一家人只剩下了在国外留学的儿子。我们无法知道这样的人，这样的家庭到底有多少。

并不止武汉市里的人感到绝望，流落在外地，外国的武汉人也遭遇了非常大的困难，当地宾馆不敢让他们住，交通拒载武汉人，一时间出现了很多流浪在街头的外地武汉人，幸好还是有好心的宾馆经营者愿意收留他们，还是有善良的司机们愿意放他们回到封城的武汉。

疫情也考验着人们的良心，世上有善就会有恶。在网络上的求助者，他们收到的最多的留言是质疑造谣，人身侮辱，当事人不仅要承受求医无果的绝望，家人去世的悲伤，还要承受网友的谩骂。网上还充斥着对病患的歧视，诋毁，有一位武汉开车到内蒙自驾游的患者被称作“千里投毒”；杭州接收了多架载有湖北市民的飞机，为此杭州居民不断抱怨自己倒霉，并且翻出了一些过时的地域歧视言论“天上九头鸟，地上湖北佬”；上海市民抱怨隔离在宾馆的人伙食太好，浪费上海市民交的税。疫情不仅夺去了生命，还在撕裂社会。

不止疫情为武汉带来了困难，封城行为本身就会带来许许多多的困难。首先是医疗物资无法交送到前线医院上。封城伊始，所有捐赠的医疗物资需要经过武汉红会的审查才能送给院方，一位美籍华人捐赠的物资被挡在了武汉市外，进到了武汉市的物资却堆在了红会的仓库里，无人派送，医院只好自己去领取。不知为何，接受病患最多的武汉协和医院被告知没有他们的物资，在他们的眼前，一位武汉政府官员领走了一箱医用口罩。幸好武汉协和医院的捐赠者联络了直升飞机送物资，这样捐赠物资就可以直接送到医院的手里。不久后，一家专业物流公司接手了武汉红会的物资医疗派发任务，2两个小时内就解决了过去一周都没有整理好的物资。





--------------------------------------------------------------------------------------------------------------
没写完，太困了，明天再写。

**Comment by liaodapo** [comment]
这周的作业，老师要求我们模仿一位生活在公元前400年的历史学家，修昔底德；猜想这位经历过瘟疫的“科学历史之父”如果穿越到今天的武汉，会如何下笔。

刚接到任务，我立即就打定主意：要扮演修昔底德、用他第一人称的视角记录这次奇妙的穿越之旅。为此我还特意去翻阅资料，以试图模仿他在当下的行为。但经过多次审题、考虑了自身情况，我最终还是选择以这样的方式来表达。

通过资料，我初步了解修昔底德写作的目的：是为帮助之后的研究者获得过去的正确知识，以警惕后人。所以他写作时更注重记录事实，而不是抒发自己的情感。比如雅典爆发瘟疫的期间，他其实也曾受瘟疫侵袭，最终幸免于难。但在他所记录的大量绝望现象里面，却没有一处正面说明了相关自己劫后余生的感触。

所以他来到此刻时也必然如此：也许他会为现代科技惊叹并极度渴望写下这段珍贵的旅程。但他一定不会在自己的文章中留下惊喜和夸张、形容他看见的某个会发光的神秘黑镜子有多么的神奇。他只会问清楚这东西后，在文章中直截了当地称它为电脑，且只作必要的说明；
也许他会在网上搜索他在意的任何事，甚至尝试连续点击20分钟的超链接，看看这无尽的蓝色字条是否真的没有尽头。但他在文章里，一定只会说：“有人在因特网撒谎…有人在因特网反抗……”

但修昔底德不是无情的怪物，他在使自己文字冷静的同时，也一定会为内心最深层次的感受，用上自己擅长的对比法：比如先写上因特网上哀哭连篇的叫喊，再写上我领他离开电脑之后，在路上看见的平静和那家能吃遍世界美食被称为“便利店“的商铺。

而我也在了解了这些以后，把修昔底德的清晰简单和自律融汇到自己的文章里。按照老师要求的，先想清楚再落笔；按照作业要求的，以修昔底德的笔法写出500字；说明了，假如修昔底德穿越到今日之武汉，他会怎么写？

**Comment by liaodapo** [comment]
点赞大妈，因为清晰简单，而且也自律了，没有让修昔底德学会代码体

**Comment by xysjou** [comment]
Karina-Han 和 大妈 的文章，我都点赞。

说下我的原因，这两篇文章都是按照王老师的要求写：
假如修昔底德穿越到今日之武汉，他会怎么写？

我也是想这么写，但有个问题是。我们在这段时间里，已经产生海量的信息，单是收集、整理、分析这些信息，就是不可估量的一件事。还要从这些事情里不偏不倚地写出来。

这让我想起王老师上课讲的《林登·约翰逊传》的故事。

我忽然明白，为什么司马光要花二十五年时间，写一部《资治通鉴》。

> 司马光为宋朝宰相，其为人所崇敬，不仅与范仲淹齐名，他还是包罗万有的一部中国史（至五代）《资治通鉴》的作者。这部书全书二百九十四卷，附录考异三十卷，学富识高，文笔精练，为史书中之北斗，后世史学著作之规范。初稿（长编）多于成书数倍。他写作此书时，一直孜孜不懈，每日抄写，积稿十尺，最后全稿装满两间屋子。此空前巨著费去作者二十五年功夫。
> 
> ——《苏东坡传》

**Comment by guoguodehezi** [comment]
### 古典文体 分析修昔底德的《伯罗奔尼撒战争史》第七章 《瘟疫》

老师在课堂上讲过，古典文体有一个隐喻“看世界”，需要模拟两种体验：1.向读者展示世界，2.与读者对话。其中有四个要素：真理真相、展示展现、场景设定、角色设定。

可以用这些工具来分析修昔底德在《伯罗奔尼撒战争史》中描写瘟疫的文字为何是古典文体。

首先，展示世界的窗口，我将它命名为“时空舞台”。第47节被放在开头，就起到了一个总起下文和搭建时空舞台的作用。时间，以战争来纪年，简单几句话就让读者清楚了瘟疫发生的紧张背景。空间，是阿提卡地区，尤其突出了雅典。作者把追光灯从入侵者身上转移到受瘟疫蹂躏的雅典人身上，称谓也从“宙西达姆斯之子，拉栖代梦之王”变成（伤害过这么多）“人命”，这种急速降落，营造出瘟疫面前，人人平等的悲怆感。最后说到医生和神庙，是讲出无论在现实还是宗教层面，没有任何力量能够拯救雅典人，甚至医生本身就是牺牲最大的一个群体。这里不用写绝望，绝望已经渗透出来。以下几段，都是本段各个层面的事实延伸。

其次，与读者对话，这就涉及到“我”是谁？“你”是谁？我要告诉你什么真相？又是如何告诉给你的？在第48节，作者直接说，他是要“记载”现象，“描述”症状。所以我认为，作者是非常自觉地要给后代的人留下一份客观记录。但这种客观没有局限在医学上，他把瘟疫缘起的猜测，瘟疫给人们带来的心理、社会影响以及对之后战争走势的影响也如实记录上去了。他对话的读者是后代的人，对话的主题是战争如何摧毁了雅典，而现在讲到的瘟疫，就像雅典这个垂死之人身上最醒目和致命的创伤。最为详尽的描述，在疾病症状这个部分，他忠实地履行了给自己立下的描述症状的职责。触目惊心。除非是亲身经历过疾病或者是天天和症状打交道的医生，否则很难写出这种切肤之痛。但如果真的经历过这些，又能沉静叙述灾难的微小细节和宏观发展，这得是一颗多么强大和坚定的心。

最为经典的部分，是社会心理和社会秩序的崩溃。疾病也许不同，这种因为绝望放弃信仰陷入混乱的过程却是可以跨越时空和民族文化局限的。这一部分能够写得甚至让我这个几千年后的异乡人都能感同身受，从中找到自己的影子，我只能说，修昔底德这场与未来的对话，非常成功。

文章结尾，又回到战争的主题。读者会很惊讶地发现，虽然他使用了“蹂躏”这样的词语，我们却不太能感受到他站在哪边。他似乎是在代表着这里的土地人民和文明秩序说出了“蹂躏”这个词，而并不是参战的任何一方。对比一下这几天看到的新闻标题“新冠或在各国爆发，美股大跌”，虽然用的词每一个都那么冷静理智，我怎么就读出了一点幸灾乐祸的味道呢？

_______________________________________

没有想到今晚工作竟然又通宵，这篇作业提交太晚了，而且只写了分析的这一半。因为“今日武汉”我写不出来。老师虽然在zoom会议上已经很到位地点拨过我，可靠媒体就是真相，我还是找不到真相在握的感觉。这大概是我自己的问题。很长时间以来，我的心理状态就跟瘟疫下的雅典一样，每一天都当做最后一天来过吧。而且真的是稍微动点真心真感情，就会被现实啪啪打脸。构思的文章题目叫《多难穿帮》，但也还是写不出来。抱歉大家，想了想还是把半篇作业交上来。赶不上参与咱们的投票和合了，留着这个遗憾吧。

**Comment by xysjou** [comment]
2020 年 1 月18 日，英国 BBC 中文网于 发布了一篇名为《武汉新型冠状病毒可能「已感染上千人」》的新闻，「科学家向 BBC 说，研究显示，在中国感染这种神秘病毒的人数远远超过官方数据。」

与此同时，绝大多数中国人正沉浸在即将到来的新春浓烈的气氛中，城市张灯结彩，农民工开始回乡，不少公司按照既定的时间陆续放假……人们并不知道 2 天后事情会有何种变化，哪怕从去年开始出现的一些预警，也掩盖在一些「谣言」声中。
 
中国的新闻一向受到政府的严管，纵容如此，网络上依旧会出现「漏洞」。人们一开始了解武汉爆发的新病毒，并不会通过官方媒体，多数人会通过微博、微信、朋友圈等社会公众取得信息。在以往多次所经历的事件表明，一些偶发的事情会在民意的推动下下，中国政府才会采取必要的措辞。
 
现在我们再回头去看微博、微信上信息，会出现许多无法显示的状况。这是中国两大社交媒体处理方式的做法。微博会采取删帖的方式将消息掩盖。微信则会利用技术手段进行「科学阉割」，微信所发的文章，会采用删除或禁止转发处理；朋友圈的敏感信息，会进行屏蔽；人们在微信群里聊天，触碰敏感信息，也会收到群警告。两家媒体所采用最极端的方式，自然是让使用者无法登陆账号。至于账号是否属于个人财产，现目前还没有统一的答案。
 
人们似乎对这种处理方式习以为常，保持沉默是多数人的选择，因为在一党专政的权利面前，要么隐忍，要么沉默，要么顺服，反抗必被镇压，真话并不会带来真相。
