### ISSUE TITLE
s04e04 克服知识的诅咒

### ISSUE THREAD

**Issue by Karina-Han** [GC4WP/GC4grace42#8]
# s04e04 克服知识的诅咒

## 要求
- 小组合作
- 结合你自己熟悉的**专属领域**，克服知识的诅咒，面向其他组的成员，
- 用500字，**介绍**一个**知识**或**技能**
- 各组员于评论处贴出初稿
- 投票决定和合初稿
-交作业方式：发送邮件到 coursework@bitcron.com
-文章会自动发布在 haozhongwen.com

## 计划
- 200302 前, 各自回复 Issue 提交自己的 500 字
- 200303 晩, zoom 会议内部讨论明确小组内容主体
- 200305 前, 轮植主笔尝试多次和合
- 200306 2042 提交作业

## 和合技操作指南
和合技之 BLAME 界面
https://github.com/GC4WP/GC4grace42/blob/master/s04e04_dama.md
**感谢大妈的辛勤付出！**

**Comment by Karina-Han** [comment]
By Karina

# 实证周期

实证周期，是从观察中得到知识，认识世界的步骤，如下图所示，实证周期是由观察，归纳推理，演绎推理，测试，评估所组成的闭环。
![image](https://user-images.githubusercontent.com/59736363/75625086-b8ec1a80-5c0e-11ea-9db7-2f9779ebf411.png)

首先，人们对事物进行观察，收集数据，比如某人观察到所有的天鹅都是白色的，因此他做出归纳推理：天鹅是白色的。由此“天鹅是白色的”变成了一条假说，或者说是常理，如果遇到有人问：“澳大利亚的天鹅是什么颜色的？”，根据归纳出的常理可以预测“澳大利亚的天鹅是白色的”。这样的推断过程就是演绎推理，由公理推断出结论。在测试阶段，将会再次观测，收集数据对常理“天鹅是白色的”进行验证。此时人们发现在澳大利亚有黑色的天鹅，该发现反驳了常理“天鹅是白色的”，因此做出评估，常理“天鹅是白色的”并不准确，需要修改最初做出的常理，断言，修改后的常理为“有的天鹅是白色的，有点天鹅是黑色的”。

然后，再次对这一常理再次进行观察，并重复整个实证观察活动，不断修正“常理”，并在周期循环往复中逐步接近真相，增加对世界的认知。

使用实证周期的研究方法叫做观察研究，是社会科学中常用的方法。社会科学中没有一成不变的定律，人们永远在发现新的证据，修正已有的理论，假说，虽然无法得到真相，但是永远在接近真相的路上。并且，通常人们并不会用相悖的观察证据来否定整个理论，而是为原理论加上了条件，使原理论的适用范围更窄，比如用“部分天鹅是白色的”来修正“所有的天鹅都是白色的”。如果观察结果支持了最初的假说，也不能说明该假说成立，只能说明该假说被暂时证明，有可能在将来发现与假说不符合的观察证据。

**Comment by liaodapo** [comment]
《必胜之法》

双胞胎兄弟常常为各种事争执。他的衣服比我新；他的包子馅儿比我多；你那一节冰棍要比我的甜。就连谁先洗脸刷牙都要每晚决议先后。摔跤、掴掌、石头剪刀布，我们从生活中演变出各种决议胜负之法。小到比谁先吃完饭，大到谁敢去拉霸王花的辫子。中间有一段时间，我们因为可耻的媚外心理，模仿史努比，坚持使用了好一段时间的井字棋。

这是一个几乎无法分出胜负的游戏，但我却因为偶然发现的诀窍，占了好一整子甜头。井字棋就像是迷你版的五子棋，优先用三枚棋子连成直线的一方获胜，整个棋盘也只有3x3的大小，九个格子的边框重合处刚好成一个“#”。所以只要是任何能写出一个井字的平面，就能马上开玩。一般由我宣战，因为这样才更有机会拿到先手，这也是获胜的第一步。

气势和第一枚子要落在九个格子的正中央，这样才占据更多机会，因为周围八个格子都是与你相连的。然后你需要对他进行一些诱导，比如在下第一步棋的时候就表现出犹豫不决。只要能让他的第一枚子落在你上下左右这四个方向，那么你就赢了。此刻只需要在他这枚子的斜角方向再放上一枚棋子。你的第二枚棋子必然会和第一枚相连，再连一枚就能获胜。而他的下一子也必然会落在阻扰你的位置。

此时你的第三枚棋子放在与他第二子最远的格子里，和你之前的两枚形成一个三角。你就会获得五子棋中的“活二”，也就是说，你会发现有两处空缺都能连成直线，下一枚不管他堵上哪处，你都还剩一处空缺可以获胜。这样，你就能先用厕所了。

这个方法我沿用至今，非常有效，街坊邻居、同学同事无不为我棋艺所折服。但回过头来，认真的同学会发现我只说了“他的第一步棋如果落在上下左右”的必胜之法，那他如果不下在这四个方向、落在斜上、斜下怎么办呢?

这位同学问得非常好。这就是我们下节课要讲的内容了，下课。

**Comment by guoguodehezi** [comment]
### 焦点短程疗法的个人应用

焦点短程疗法(Solution-focused Brief Therapy, SFBT)是聚焦问题解决，在认知行为层面工作的一种心理治疗技术。它要求来访者（求助者）具备基本正常的认知和行为能力，所以并不适合严重的神经症和精神病患者使用。
怎么检验自己是否适用这种技术呢？请回忆最近一次发怒的体验，比如我和我老汉吵架：只要在吵架的任意阶段（包括吵完之后），我曾经在内心想过：我现在是愤怒状态，我说的有些话夸大了，这样做不是因为事实是这样，而是要在气势上压倒他——不需要说出来，只要这么想过，那就证明你有基本的认知能力。如果在有认知之后，还有主动的示好行为，“死鬼，来吃饭啦！”这就说明你有基本的基于认知的行为能力。
在实际应用中，我想，既然来访者有这种能力，如果抛开疗法的标准设置，没有咨询师（治疗师）和督导的参与，没有一面墙是单向玻璃的咨询室，只是一个普通人希望运用这种技术解决自己的困惑行不行呢？于是就设计了可以给自己使用的简单流程。
一、	明确问题阶段。准备一张纸，一支笔，分为左右两栏，左边写问题，右边写回答。给每一步提问和回答前做好标号，便于最后追踪，问题是在哪一步得到了重大突破的。问题和回答都应该真诚，每一步的回答目标是把问题具体化，一旦出现绕圈或者越问越迷惑的情况就应该停止。
举例：
1	我和老汉为啥老吵架？	        - 因为他是杠精
2	杠精的表现是啥？	                - 不管我现在啥情绪，都要打破砂锅问到底
3	他问的内容是什么？	        - 刚才事情是怎么发生的？我的话到底是啥意思？我是生气了吗？
4	哪些问题是惹火我不该问的？	    - 我生没生气他看不出来吗？
5	他看出来的正确方法有哪些？	      -   ……

从这个例子可以看出来，问题实际上是把抽象概念和标签，转化为具体表现，具体内容，关键触发点，具体方法。如果我们要解决问题，那么首先就要把问题分解为可以解决的小步骤。

写到这里发现字数超了，又发现还有且听下回分解这种操作，好吧，那就留点期待给下集。

**Comment by xysjou** [comment]
**《新手如何建博客网站》**

建网站需要做两件事：1、申请域名；2、买空间。这里之所以不推荐用服务器自建，原因很简单，用服务器，需要懂代码，买空间就不要。

申请域名：域名的申请，最简单的方法就是去各大平台花钱买。当然有免费的域名（一年使用权限），不过限于墙太高，很难注册成功。个人推荐去买域名，买好按照国情，需要备案，请准备好身份证照片、视频录像、手持身份证照，接下来就是20天左右的等待时间。

购买空间：空间和服务器，前者是已经有人帮忙搭建号后台，只需要使用即可；后者需要自己去建后台，随心所欲。简单来说，空间适合新手，后台需要学程序。

搭建好空间，就需要装对应的安装包，博客最常用的就是 WordPress，这时只需要到官网下载安装包，通过 ftp 软件进行安装，最后通过绑定申请的域名（国内需备案通过），即可成功访问。

**Comment by ZoomQuiet** [comment]
blog 网站, 最简单的不是 WP 了...
直接使用 github-pages , 5分钟,就获得一个网站...
免费, 不用任何空间和服务器

**Comment by Karina-Han** [comment]
> blog 网站, 最简单的不是 WP 了...
> 直接使用 github-pages , 5分钟,就获得一个网站...
> 免费, 不用任何空间和服务器
--------------------------------------------------------------------------------------------------------------
理念不同，怎么能成为评论文章好坏的原因呢？

**Comment by leyafo** [comment]
**普通人如果使用英文 google 搜索引擎？**
使用搜索引擎是个非常有用的技能，由于一些特殊的原因你用中文或其他搜索引擎总是无法找到你想要的内容。这时改用英文搜索效率和正确率相对中文会大大提升。英文搜索不用太高门槛，平常惯用中文搜索的人都能做到。以下我们拿“**新手如何建博客网站**”这个问题来作为实例讲解如何使用英文搜索引擎。
首先我们确定好英语句子里面的疑问词，一般是 what, why, how 这几个词。上面这句话里有"如何"我们就可以把他翻译成 how。  
其次找到关键动词 verb。这里是“建”，我们可以对应的翻译成 building 或 create，constructe 都行，实在不行用百度搜索一下“建”这个单词的翻译就行。
剩下的就是作为关键信息的名词：博客。这个我们都知道叫 blog。
整句话我们替换成英文搜索可以变为：  
*how building blog*  
不要在意语法或拼写错误， 搜索引擎会根据关键字给你想要的东西。你可以把这句错误的英语句子放到 google 里试试，看看能不能给你想要的东西。

**Comment by wamgel** [comment]
**什么是瑜伽**

瑜伽，词源梵语yuj-或yug-，指牲畜拉车的轭，意为控制、结合，后引申为联结之意，产生yoga一词。

那么，瑜伽是什么的联结？

首先，瑜伽起源于印度。古印度人认为人世间虚幻不真，唯一真实的，只有梵 。人的终极意义，是超脱生命，追求真实，从小我走向大我，投身于梵之中，直至梵我合一。

但是，梵究竟是什么？ 印度人也没说清楚。就像基督教解释上帝，无法用逻辑证明的事物只能用否定法。祂不是这个，不是那个。排除所有可能以后，剩下的就是答案。所以，梵是非概念的，不能靠逻辑思辨来学习，只能通过瑜伽直接体验。

瑜伽，就是联结个人（小我）与梵（大我）的途径，是印度流传了两千多年的修行方法之一。通过瑜伽这种方式来修行的人被称为瑜伽士。

看到这里，是不是觉得上面这些和我们日常接触到的瑜伽完全没有关系？那些像做体操一样，把身体扭来扭去，摆出各种造型的到底是什么？

这些造型，在瑜伽里的专有名词叫体式/体位，属于瑜伽八支中的第三支。

> 禁戒（Yama）:是指外在控制，宇宙的道德戒律。
> 遵行（Niyama）：是指内在控制，通过自律进行自我净化。
> 体位（Āsanas）：是指瑜伽姿势，也称调身。
> 调息（Prāṇāyāma）：系统的呼吸方法，呼吸的控制和能量的处理。
> 制感（Pratyāhāra）：精神从感觉和外部事物的奴役中解脱出来，是指感觉消失，控制内心，也称调心。
> 专注（Dhāraṇa）：集中注意，一心一意。集中专注力以提升生命之气。
> 禅那（Dhyāna）：即冥想。
> 三摩地（Samādhi）：由冥想而来的超意识全部集中到灵魂中，和宇宙合二为一。超越意识的境界。身体和感官静止，看似在睡眠，但头脑仍保持警惕。

前七支都是为了最后第八支——三摩地，既梵我合一。

练习体式，是为了调整身体，能稳固、持久的打坐冥想，直至三摩地。

但它仅仅是八分之一。
