### ISSUE TITLE
s04e05 抽象阶梯

### ISSUE THREAD

**Issue by liaodapo** [GC4WP/GC4grace42#9]
## 题目 ##

以小组为单位，采访并描写本组中的一个成员，在讲述这位成员的故事时，在阶梯顶端创造意义，也在底部去做例证。 600字以内。

> [聊颇采访大妈的录音链接](https://zoom.com.cn/rec/play/7J0lcb-g-Go3SdGc5ASDAf4qW424e6is03RP-KFfmk6zUXIFZFShZ-MSa-K69THIWrZOHO_0dVuLHk2B) 

## 资源 ##
- 200211 首次 zoom 直播会议
录像链接:https://pan.baidu.com/s/1Fbdf5ZV8h1CBpy76R4o4mg  密码:9iit

- 有关和合技:
「私塾7.1/36」和合技C-C模式 - 简书 
 https://www.jianshu.com/p/d90f5df63e18

**Comment by liaodapo** [comment]
# 人之善

两个自称社交障碍的人，被迫要采访对方42分钟。
一次差不多约好的活动，只有两人实际到场。
这两人认识三个月，但却从来没有问过对方以及周围任何人的任何私人问题。

“我们在年前就认识了，对于感兴趣的人想问他什么你从来就没有准备过吗？”
一人在采访的最后诘问至此。两人却依旧坚持到采访的最后一刻。就像两人为什么要准时到场一样。

我在刚得知要采访他的时候准备了两个主题，「结婚状况」和「对游戏的看法」。外加「职业工资水平感悟」、「人生被霸凌经历」等更具冲击性的话题。但奈何不了体内怂性，我一开口就只剩：“您对游戏有什么看法？玩游戏吗？”，没聊到两秒，话题又急转至「对不同娱乐形式的看法」。

整个采访过程没有一次停顿超过两秒。我不敢打断，怕他说得太少我抓不住细节、怕编织问题的时间不够。但又很想打断，因为他说的太多了，该到我计划的下一步了。
他的答案无限衍生，仿佛我每结巴一次他都可以用“那”、“OK”、“哈哈没关系”立刻从另一个角度展开。除非我拼老命打断，或者问出一个确切的问题。

我俩的行为都充分展现了自己的目的：得知我未听闻《东京爱情故事》，他会立马换一个角度说明；聊到冷门的作品，我会叫他说一段；讲到激昂时我也想说说自己，但又立即说“不重要”带过。因为这是我问他答，还有其他人听。

到23点40分我宣言要问最后一个问题：
“大妈，你看过这么多漫画，如果要尽可能推荐一部大众喜欢的，会是哪一本呢？“
“那当然是风之谷啦。宫崎骏的《风之谷》。“

## 
 给还准备归纳这次采访的小伙伴的线索：
 - 我晚于《东京爱情故事》出生；
 - 整通采访出现了两个时期的作品；
 - 出现了雅、俗、雅俗交织的作品；
 - 王道，这个词在采访中出现的两种相似的解释，只要愤怒就一定能够赢，和胜利者说的话；
 - 我和大妈都说过一句话：没听说过、没听说过吧；
 - 我在采访最后提到的一个词，流传。
 - 采访开头大妈说：约定就是约定。这句话可以是大妈参加采访的理由。我的这篇文章，也可以是我坚持采访的理由，就算我们一个人困得不行明天还要上班，一个人已经被老婆嫌弃，要睡沙发了。
 

（需要特别说明的是：我在采访中说giao这个词带感，是我从生理感受上分析出的，不是随风而屈。和哗众取宠的skr不同，giao念起来有一种被掐住咽喉的感觉，但是又没有真的被掐住。有一种发挥出了口腔全部的力量却又刚刚好的感觉。就像是超级赛亚人积聚元气毁灭粑粑星球后，虽然很累，但很欣慰——虽然风吹过来我才会叹就对了）

**Comment by liaodapo** [comment]
### 追加[大妈关于采访的分享](https://fm.101.camp/2020/gc4wp-iv-s4e05.html?from=groupmessage)和一条线索：
- 虽然表现的不明显，但我和大妈基本都能听懂对方在说什么，并没有所谓的“代沟”。起码反应是真得快——可能真的是都怂性大发了

**Comment by guoguodehezi** [comment]
### 风之子

我们组定下来的采访对象是大妈。

没能直接采访到这位大神非常遗憾，不过聊颇同学超额完成了任务。感谢聊颇同学，锲而不舍地追问大妈，对于当下土味视频，“giao”这些流行前沿事物的看法，使大妈暴露出了具有共性的思维方式。这一点和采访内容，容后再说，我先说说我听完录音之后对大妈的进一步了解。

1.	大妈的童年生活在中国北方一个国有厂矿，这个单位配有俱乐部，学校也会定期组织学生前往观看电影。初二看到了《天空之城》。查资料，这个片子在中国播放，应该是在1989到90年代初期。小学高年级到初中阶段，是人生观形成的时候，这个时期基本上会完成个人心灵史的轴心时代，此时提出的问题，有些会用一生去回答。我也算是大妈的同时代人了，有幸在这个阶段经历了80-90年代中国在思想文化上的黄金时期。当轴心时代遇上黄金时期，总有一些矿产要留下来。

2.	大妈对游戏的态度：小时候穷，长大看穿了游戏的程序。我想穷不能完全解释，因为热爱漫画在那个时代也很烧钱。恰好我有个沉迷游戏的表弟，所以知道游戏对男孩子意味着什么，那不仅是娱乐，那是社交活动。所以聊颇说到的一点是可信的，那就是采访者和被采访者恐怕确实都有一点社交障碍。

1995年，互联网进入中国寻常百姓家。这个巨大的风口，到现在依旧风头正劲。大妈这个风之子，也开始乘风翱翔了。
全部的采访内容，句句不离网络，这是一个被网络塑造同时也在塑造网络的人。

漫画是大妈认识世界的媒介，也是内心世界的外挂。大妈的头像，和一张只拍了头顶小辫子的照片，都显示出同样的漫画风格。大妈力荐的《风之谷》里一定有解开所有问题的钥匙，有空一定看看。

那么我开始说到的大妈在面对不同问题时的共性思维是什么呢？就是“赋值”和“变量”思维。这两个词是我今晚才学到的，为了了解大妈在做什么，报了个python小班，用了一个小时通关一节课，学到了这两个可以描述大妈思维方式的词。
举个栗子，说到“土味视频”，大妈用了一个词“塑料儿童”；说到愤怒情绪，大妈用了一个定义“所有负面情绪都是指向自己的无能”；说到“giao”，大妈说到了一个现象“方言网络化”。不得不承认，这些标签都好精确啊。大妈的世界里，一定有无数个这样集装箱，所有的现象，都可以找到准确定义的类别存放。或者反过来说，一个现象，哪怕自己并不了解，一样可以扔进某个盒子里。这大概就是大妈的“抽象阶梯”了吧。


后记：
非常惊讶得发现，我和大妈这两个几乎生活在同时代的人，除了不爱打游戏一样，其他方面完全不同。《东京爱情故事》被推荐过无数次，死活看不下去。漫画从来都觉得是拍成电影更好看。网络小说尝试着读过一点，读不进去。技术流的东西，除非要用，绝对不学。连群里的投票都是现搜来的方法，现用。大妈如果是属于风的，我大概就是属石头的。

**Comment by xysjou** [comment]
**大妈的漫画世界**

在 43 分钟的采访时间里，很难形象描述 Zoom.Quiet。打开谷歌引擎，网络上的介绍是：

> 中国 Python 用户组联合创始人，江湖人称「大妈」，Python 中国社区联合创始人，中国 Python 社区中最长情的贡献者……

换一个词，继续搜索，输入：是也乎。弹出来第一个网站：[钩陈/ 什么是程序媛?/ 是也乎(￣▽￣)/ ZoomQuiet.io](https://blog.zoomquiet.io/oldtouch-codeing-lady-380s.html)，进入，点击栏目一行的「大妈」，网站会出现一张巨大的树状图，这是他的个人履历。如果对域名好奇，可以继续搜索： .io 域名，会在维基百科里找到这么一种解释：

> 在计算机科学领域，「IO」常被作为「I/O」（输入/输出；Input/Output）的缩写，这使得 .io 域名很适合与技术相关的服务。

简短的采访，喜欢用「是也乎」作为口头禅的 Zoom.Quiet，没有聊技术，话里话外，无不对生活充满热情，用他自己的话说，「25岁之后，不能以外貌为主，要学会找到一个讨好自己的招数，学会控制自己的情绪，无论是吃、看、玩，要有固定的品类。」

他喜欢漫画，说了许多只有资深漫画迷才知道的名字：高屋良树、弐瓶勉 、川口开治、村上纪香……所有的漫画家里，唯一让人印象深刻的，或许就是宫崎骏。

Zoom.Quiet 是一位资深漫迷，看完动漫不说，还会去把漫画找来读一遍，但他不玩游戏，这和他的童年有关。

Zoom.Quiet  接触游戏很早，街机开始流行，已有所尝试，逃课和同学打游戏，别的同学玩一把就通过，他没多久就死了，再之后上大学，学计算机，发现游戏是程序员写好的代码，明白游戏是怎么回事，就绝了别人设定好的游戏，投入漫画的怀抱。

在日本，漫画是一个无限广阔的世界，一位好的漫画家，可以担当剧作家、摄影、导演、美术、音乐等多重角色，这一门类的创立缘于阿童木之父：手冢治虫。一个细节能表现日本漫画的重要性：政府发布通告，会出相应的漫画。「可以说，漫画在日本是独立的艺术作品。」

生活中的 Zoom.Quiet  ，不看土味视频，对流行词汇的了解，明白应用情景即可，互联网已经给很多流行词汇下了「速朽」的定义，不需要浪费太多时间去明白。如果你在网络上看见「是也乎」这三个词时，相信这就是 Zoom.Quiet  ，你可以跑过去叫他：大妈。他会推荐你看宫崎骏的《风之谷》，说不定还会叫你把漫画再看一遍。

**Comment by liaodapo** [comment]
我赞[大妈的作业](https://github.com/GC4WP/GC4grace42/blob/master/s04e05_dama.md)
